// DetMath: the simulation's transcendental functions, which must give the same
// bits on every platform.
//
// They exist because libm does not. test_determinism's canonical scene hashed
// to one number on Windows and another on Linux, and the whole difference was
// one-ulp disagreements between the UCRT and glibc - the first an atan2f in
// EulerFromRotation on tick 29 (docs/planning/2026-09-10-cross-platform-
// determinism.md).
//
// THE GOLDEN TABLE is the heart of this file. It was produced by a Python
// transcription of DetMath.hpp, operation for operation; Python's floats are
// IEEE doubles with no contraction, so the table is what any conforming
// platform computes. A row failing here means this compiler reordered,
// contracted or substituted an operation somewhere in DetMath - which would
// otherwise surface as a replay that stops reproducing on one machine.
//
// The same transcription measured accuracy: over 100,000 random inputs across
// the five functions, every result was the correctly rounded float.

#include "TestHarness.hpp"

#include "core/DetMath.hpp"

#include <glm/gtc/quaternion.hpp>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <limits>
#include <string>

using namespace Supersonic;

namespace {

enum class Fn { Sin, Cos, Asin, Atan2, Pow };

struct Row {
    Fn fn;
    uint32_t a;
    uint32_t b; // the second argument of Atan2 (x) and Pow (the exponent)
    uint32_t expected;
};

// Generated by detmath_ref.py. The first ten are the calls the probe found
// glibc and the UCRT disagreeing on, and the damping factor every body takes
// every step; the rest spread over every quadrant and branch.
constexpr Row kGolden[] = {
    {Fn::Sin, 0x3f063276u, 0x00000000u, 0x3f00228bu},
    {Fn::Sin, 0x3e7eb9d9u, 0x00000000u, 0x3e7c1b66u},
    {Fn::Cos, 0x3f8d3024u, 0x00000000u, 0x3ee6db59u},
    {Fn::Cos, 0x3fade678u, 0x00000000u, 0x3e57aa8cu},
    {Fn::Asin, 0x3df787feu, 0x00000000u, 0x3df8234cu},
    {Fn::Asin, 0x3d1ae79du, 0x00000000u, 0x3d1af112u},
    {Fn::Atan2, 0xbd002dd0u, 0x3f7f9124u, 0xbd005aa7u},
    {Fn::Atan2, 0x3cfa18e1u, 0x3f7fe0ecu, 0x3cfa2359u},
    {Fn::Atan2, 0xbd7eb5d0u, 0x3f7ecf53u, 0xbd7f9156u},
    {Fn::Pow, 0x3f733333u, 0x3c888889u, 0x3f7fc7ffu},
    {Fn::Sin, 0x3dcccccdu, 0x00000000u, 0x3dcc7577u},
    {Fn::Cos, 0x3dcccccdu, 0x00000000u, 0x3f7eb898u},
    {Fn::Sin, 0x3f000000u, 0x00000000u, 0x3ef57744u},
    {Fn::Cos, 0x3f000000u, 0x00000000u, 0x3f60a940u},
    {Fn::Sin, 0x3f490fdau, 0x00000000u, 0x3f3504f3u},
    {Fn::Cos, 0x3f490fdau, 0x00000000u, 0x3f3504f4u},
    {Fn::Sin, 0x3f800000u, 0x00000000u, 0x3f576aa4u},
    {Fn::Cos, 0x3f800000u, 0x00000000u, 0x3f0a5140u},
    {Fn::Sin, 0x3fc90fdbu, 0x00000000u, 0x3f800000u},
    {Fn::Cos, 0x3fc90fdbu, 0x00000000u, 0xb33bbd2eu},
    {Fn::Sin, 0x40000000u, 0x00000000u, 0x3f68c7b7u},
    {Fn::Cos, 0x40000000u, 0x00000000u, 0xbed51133u},
    {Fn::Sin, 0x40490fdbu, 0x00000000u, 0xb3bbbd2eu},
    {Fn::Cos, 0x40490fdbu, 0x00000000u, 0xbf800000u},
    {Fn::Sin, 0x40800000u, 0x00000000u, 0xbf41bdcfu},
    {Fn::Cos, 0x40800000u, 0x00000000u, 0xbf275530u},
    {Fn::Sin, 0xbe99999au, 0x00000000u, 0xbe974e6du},
    {Fn::Cos, 0xbe99999au, 0x00000000u, 0x3f7490efu},
    {Fn::Sin, 0xc0200000u, 0x00000000u, 0xbf193578u},
    {Fn::Cos, 0xc0200000u, 0x00000000u, 0xbf4d17bfu},
    {Fn::Sin, 0x40c90fdbu, 0x00000000u, 0x343bbd2eu},
    {Fn::Cos, 0x40c90fdbu, 0x00000000u, 0x3f800000u},
    {Fn::Sin, 0x41200000u, 0x00000000u, 0xbf0b44f8u},
    {Fn::Cos, 0x41200000u, 0x00000000u, 0xbf56cd64u},
    {Fn::Sin, 0x42c80000u, 0x00000000u, 0xbf01a12eu},
    {Fn::Cos, 0x42c80000u, 0x00000000u, 0x3f5cc0eeu},
    {Fn::Sin, 0xc47a2000u, 0x00000000u, 0xbf7eca46u},
    {Fn::Cos, 0xc47a2000u, 0x00000000u, 0x3dc6dffcu},
    {Fn::Asin, 0x3a83126fu, 0x00000000u, 0x3a831270u},
    {Fn::Asin, 0x3e800000u, 0x00000000u, 0x3e815f4eu},
    {Fn::Asin, 0x3f000000u, 0x00000000u, 0x3f060a92u},
    {Fn::Asin, 0x3f3504f3u, 0x00000000u, 0x3f490fdau},
    {Fn::Asin, 0x3f666666u, 0x00000000u, 0x3f8f549bu},
    {Fn::Asin, 0x3f7fff58u, 0x00000000u, 0x3fc87d36u},
    {Fn::Asin, 0xbecccccdu, 0x00000000u, 0xbed2b256u},
    {Fn::Asin, 0xbf733333u, 0x00000000u, 0xbfa06a08u},
    {Fn::Atan2, 0x3f800000u, 0x3f800000u, 0x3f490fdbu},
    {Fn::Atan2, 0x3f800000u, 0xbf800000u, 0x4016cbe4u},
    {Fn::Atan2, 0xbf800000u, 0xbf800000u, 0xc016cbe4u},
    {Fn::Atan2, 0xbf800000u, 0x3f800000u, 0xbf490fdbu},
    {Fn::Atan2, 0x3e99999au, 0x40000000u, 0x3e18769cu},
    {Fn::Atan2, 0x40000000u, 0x3e99999au, 0x3fb60107u},
    {Fn::Atan2, 0xba83126fu, 0xc0a00000u, 0xc0490c94u},
    {Fn::Atan2, 0x358637bdu, 0x3f800000u, 0x358637bdu},
    {Fn::Atan2, 0x40e00000u, 0xbf000000u, 0x3fd23075u},
    {Fn::Pow, 0x3f733333u, 0x3c888889u, 0x3f7fc7ffu},
    {Fn::Pow, 0x3f000000u, 0x3d088889u, 0x3f7a2728u},
    {Fn::Pow, 0x40000000u, 0x3f000000u, 0x3fb504f3u},
    {Fn::Pow, 0x3dcccccdu, 0x40400000u, 0x3a83126fu},
    {Fn::Pow, 0x406ccccdu, 0xbfa00000u, 0x3e478c56u},
    {Fn::Pow, 0x3f7fbe77u, 0x3d4ccccdu, 0x3f7ffcb9u},
};

float fromBits(uint32_t bits) {
    float f;
    std::memcpy(&f, &bits, sizeof f);
    return f;
}

uint32_t bitsOf(float f) {
    uint32_t bits;
    std::memcpy(&bits, &f, sizeof bits);
    return bits;
}

const char* nameOf(Fn fn) {
    switch (fn) {
    case Fn::Sin: return "sin";
    case Fn::Cos: return "cos";
    case Fn::Asin: return "asin";
    case Fn::Atan2: return "atan2";
    case Fn::Pow: return "pow";
    }
    return "?";
}

float evaluate(const Row& row) {
    const float a = fromBits(row.a);
    const float b = fromBits(row.b);
    switch (row.fn) {
    case Fn::Sin: return DetMath::sin(a);
    case Fn::Cos: return DetMath::cos(a);
    case Fn::Asin: return DetMath::asin(a);
    case Fn::Atan2: return DetMath::atan2(a, b);
    case Fn::Pow: return DetMath::pow(a, b);
    }
    return 0.0f;
}

// Distance in representable floats, across zero as well.
long long ulpDistance(float a, float b) {
    auto line = [](float f) {
        const int64_t i = static_cast<int32_t>(bitsOf(f));
        return i < 0 ? static_cast<int64_t>(INT32_MIN) - i : i;
    };
    const long long d = static_cast<long long>(line(a) - line(b));
    return d < 0 ? -d : d;
}

} // namespace

static void testEveryPlatformComputesTheTablesBits() {
    int wrong = 0;
    for (const Row& row : kGolden) {
        const uint32_t got = bitsOf(evaluate(row));
        if (got == row.expected) continue;
        ++wrong;
        char message[160];
        std::snprintf(message, sizeof message, "%s(%08x, %08x) = %08x, the table says %08x", nameOf(row.fn),
                      static_cast<unsigned>(row.a), static_cast<unsigned>(row.b), static_cast<unsigned>(got),
                      static_cast<unsigned>(row.expected));
        CHECK_MSG(false, message);
    }
    CHECK_MSG(wrong == 0, std::to_string(wrong) + " golden row(s) differ on this platform");
}

static void testTheCallThatPartedTheTwoPlatformsIsSettled() {
    // Tick 29 of the canonical scene: glibc said bd005aa8, the UCRT bd005aa7,
    // and the correctly rounded answer is the UCRT's.
    CHECK_MSG(bitsOf(DetMath::atan2(fromBits(0xbd002dd0u), fromBits(0x3f7f9124u))) == 0xbd005aa7u,
              "the tick-29 atan2 is the correctly rounded value on every platform");

    // And the damping factor every rotating body takes every step, which the
    // runtimes happened to agree on - now by construction rather than luck.
    CHECK_MSG(bitsOf(DetMath::pow(0.95f, 1.0f / 60.0f)) == 0x3f7fc7ffu, "pow(0.95, 1/60) is 3f7fc7ff");
}

static void testItStaysWithinAnUlpOrTwoOfThisPlatformsLibm() {
    // Not the determinism check - the table is - but the one that catches a
    // wrong quadrant, a wrong branch or a wrong constant, all of which the
    // table could share with the transcription that made it.
    long long worstSin = 0, worstCos = 0, worstAsin = 0, worstAtan2 = 0, worstPow = 0;
    for (int i = -4000; i <= 4000; ++i) {
        const float x = static_cast<float>(i) * 0.0025f; // [-10, 10]
        worstSin = std::max(worstSin, ulpDistance(DetMath::sin(x), std::sin(x)));
        worstCos = std::max(worstCos, ulpDistance(DetMath::cos(x), std::cos(x)));
        const float u = static_cast<float>(i) / 4000.0f; // [-1, 1]
        worstAsin = std::max(worstAsin, ulpDistance(DetMath::asin(u), std::asin(u)));
    }
    for (int i = -60; i <= 60; ++i) {
        for (int j = -60; j <= 60; ++j) {
            const float y = static_cast<float>(i) * 0.083f;
            const float x = static_cast<float>(j) * 0.071f;
            if (x == 0.0f && y == 0.0f) continue;
            worstAtan2 = std::max(worstAtan2, ulpDistance(DetMath::atan2(y, x), std::atan2(y, x)));
        }
    }
    for (int i = 1; i <= 200; ++i) {
        for (int j = -40; j <= 40; ++j) {
            const float b = static_cast<float>(i) * 0.02f;
            const float e = static_cast<float>(j) * 0.07f;
            worstPow = std::max(worstPow, ulpDistance(DetMath::pow(b, e), std::pow(b, e)));
        }
    }
    CHECK_MSG(worstSin <= 2, "sin within 2 ulp of libm, worst " + std::to_string(worstSin));
    CHECK_MSG(worstCos <= 2, "cos within 2 ulp of libm, worst " + std::to_string(worstCos));
    CHECK_MSG(worstAsin <= 2, "asin within 2 ulp of libm, worst " + std::to_string(worstAsin));
    CHECK_MSG(worstAtan2 <= 2, "atan2 within 2 ulp of libm, worst " + std::to_string(worstAtan2));
    CHECK_MSG(worstPow <= 2, "pow within 2 ulp of libm, worst " + std::to_string(worstPow));
}

static void testTheEdgesAreCs() {
    const float inf = std::numeric_limits<float>::infinity();
    const float nan = std::numeric_limits<float>::quiet_NaN();

    CHECK_MSG(DetMath::sin(-0.0f) == 0.0f && std::signbit(DetMath::sin(-0.0f)), "sin(-0) is -0");
    CHECK(DetMath::cos(0.0f) == 1.0f);
    CHECK(std::isnan(DetMath::sin(inf)));
    CHECK(std::isnan(DetMath::cos(nan)));

    CHECK(bitsOf(DetMath::asin(1.0f)) == 0x3fc90fdbu);
    CHECK(bitsOf(DetMath::asin(-1.0f)) == 0xbfc90fdbu);
    CHECK(std::isnan(DetMath::asin(1.5f)));
    CHECK_MSG(std::signbit(DetMath::asin(-0.0f)), "asin(-0) is -0");

    CHECK(bitsOf(DetMath::atan2(0.0f, 0.0f)) == 0x00000000u);
    CHECK(bitsOf(DetMath::atan2(-0.0f, 0.0f)) == 0x80000000u);
    CHECK(bitsOf(DetMath::atan2(0.0f, -0.0f)) == 0x40490fdbu);
    CHECK(bitsOf(DetMath::atan2(-0.0f, -0.0f)) == 0xc0490fdbu);
    CHECK(bitsOf(DetMath::atan2(1.0f, 0.0f)) == 0x3fc90fdbu);
    CHECK(bitsOf(DetMath::atan2(-1.0f, -0.0f)) == 0xbfc90fdbu);
    CHECK(bitsOf(DetMath::atan2(inf, inf)) == 0x3f490fdbu);
    CHECK(bitsOf(DetMath::atan2(-inf, -inf)) == 0xc016cbe4u);
    CHECK(bitsOf(DetMath::atan2(1.0f, -inf)) == 0x40490fdbu);
    CHECK(bitsOf(DetMath::atan2(2.0f, inf)) == 0x00000000u);

    CHECK(DetMath::pow(3.0f, 0.0f) == 1.0f);
    CHECK(DetMath::pow(0.0f, 2.0f) == 0.0f);
    CHECK(DetMath::pow(0.0f, -1.0f) == inf);
    CHECK(DetMath::pow(0.5f, inf) == 0.0f);
    CHECK(DetMath::pow(2.0f, inf) == inf);
    // Documented: a negative base is not what DetMath::pow is for.
    CHECK_MSG(std::isnan(DetMath::pow(-2.0f, 2.0f)), "a negative base gives NaN, as the header says");
}

static void testAngleAxisIsGlmsFormula() {
    struct Case {
        float angle;
        glm::vec3 axis;
    };
    const Case cases[] = {
        {0.3f, glm::vec3(0.0f, 1.0f, 0.0f)},
        {-2.1f, glm::normalize(glm::vec3(1.0f, 2.0f, -0.5f))},
        {3.0f, glm::normalize(glm::vec3(-0.2f, 0.1f, 0.9f))},
    };
    for (const Case& c : cases) {
        const glm::quat mine = DetMath::angleAxis(c.angle, c.axis);
        const glm::quat theirs = glm::angleAxis(c.angle, c.axis);
        const float worst = std::max(std::max(std::fabs(mine.w - theirs.w), std::fabs(mine.x - theirs.x)),
                                     std::max(std::fabs(mine.y - theirs.y), std::fabs(mine.z - theirs.z)));
        CHECK_MSG(worst <= 1e-6f, "angleAxis(" + std::to_string(c.angle) + ") matches glm's to 1e-6, worst " +
                                      std::to_string(worst));
    }
}

void runTests() {
    testEveryPlatformComputesTheTablesBits();
    testTheCallThatPartedTheTwoPlatformsIsSettled();
    testItStaysWithinAnUlpOrTwoOfThisPlatformsLibm();
    testTheEdgesAreCs();
    testAngleAxisIsGlmsFormula();
}

TEST_MAIN("test_detmath", 35)
